### ISSUE TITLE
"xref invalid format" error when import the Chinese language paper

### ISSUE THREAD

**Issue by yanis791** [mgmeyers/obsidian-zotero-integration#91] opened 2022-09-17 09:49 UTC
![1663406903741](https://user-images.githubusercontent.com/58966659/190850796-edfff973-bf37-4077-9688-79f63bef8070.jpg)
when I import the Chinese language paper from Zotero to obsidian by the plugin, the error occurs. When I change the pdf name to English, the error still happens.

**Comment by carey036** [comment] 2022-09-28 08:08
still hope a better way to solve the problem, one may not be able to select text with reprinting it by `COMMAND+P`

**Comment by mgmeyers** [comment] 2022-10-01 17:49
Closing this as duplicate of #82, can continue the conversation there

**Closed by mgmeyers** 2022-10-01 17:49 UTC
